load("@io_bazel_rules_go//go/tools/bazel_testing:def.bzl", "go_bazel_test")

go_bazel_test(
    name = "notify_output_groups_test",
    srcs = ["notify_output_groups_test.go"],
    deps = ["//internal/e2e"],
)
