load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["mock.go"],
    importpath = "github.com/bazelbuild/bazel-watcher/bazel/testing",
    visibility = ["//visibility:public"],
)
