load("@io_bazel_rules_go//go/tools/bazel_testing:def.bzl", "go_bazel_test")

go_bazel_test(
    name = "lifecycle_hooks_test",
    srcs = ["lifecycle_hooks_test.go"],
    deps = ["//internal/e2e"],
)
