load("@io_bazel_rules_go//go/tools/bazel_testing:def.bzl", "go_bazel_test")

go_bazel_test(
    name = "incompatible_by_default_test",
    srcs = ["incompatible_by_default_test.go"],
    deps = ["//internal/e2e"],
)
